### PR TITLE
Adding support for armv7

### PR DESCRIPTION
**Pull request by JeroenVanOort**
# Proposed Changes

My naive try at adding support for armv7.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by frenck** [comment]
Hi @JeroenVanOort 👋 

I noticed you prefixed this PR title with "Draft:", I've removed that, as GitHub has a draft option... Which I've converted this PR too.

I wonder what this PR is at this point? As in, draft = an idea? or test? or feature request?

Please note, armv7 has been removed in v0.13.0, due to required packages not being available for 32-bits systems, has that been resolved?

../Frenck

**Comment by JeroenVanOort** [comment]
An idea and feature request; I just wanted to see what would happen and if it might actually be as easy as my changes so far. I didn't know there was support for armv7 before, nor do I know of problems with missing packages being resolved. But if we could get the correct labels on this PR, I could see what happens and what I can do if it doesn't work ;-)

**Comment by frenck** [comment]
I don’t understand, work on PR is done before making PRs?

There is no need to label anything, not will it work as the build will fail. But that of course, you already know, you test your PRs, right?

../Frenck

**Comment by frenck** [comment]
Don't worry about it, thanks for being willing to contribute.

../Frenck

**Pull request closed without merging**
