### PR TITLE
Upgrade base images and packages

### LINKED ISSUE #21: Restarting loop
# Problem/Motivation

> Issue filed because add-on regularly restarts for an unknown reason, making it unusable.

## Expected behavior

> We expect the add-on to be stable.

## Actual behavior

> Below is a log, and the add-on appears to restart and is unusable. I do not know how to access the following locations for additional logs. I am running on an Odroid C1.
```
/opt/traccar/core or core.1275
/opt/traccar/hs_err_pid1275.log
/opt/traccar/replay_pid1275.log
```

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=1275, tid=0x0000ffffa550fab0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Thu May  9 18:09:31 UTC 2019)
# Core dump written. Default location: /opt/traccar/core or core.1275
#
# An error report file with more information is saved as:
# /opt/traccar/hs_err_pid1275.log
[10/Aug/2019:20:56:34 +1200] 304 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/pickup.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[10/Aug/2019:20:56:34 +1200] 304 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/tram.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[10/Aug/2019:20:56:34 +1200] 304 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/trolleybus.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[10/Aug/2019:20:56:34 +1200] 304 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/scooter.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[10/Aug/2019:20:56:34 +1200] 304 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/truck.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
#
# Compiler replay data is saved as:
# /opt/traccar/replay_pid1275.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
2019/08/10 20:56:34 [error] 493#493: *260 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-traccar, request: "GET /images/tram.svg HTTP/1.1", upstream: "http://127.0.0.1:18682/images/tram.svg", host: "hassio.local:8123", referrer: "http://hassio.local:8123/api/hassio_ingress/8chAPLNAS8E2tKXQnBJvPbYUqyOu-VyzJVSDZNbylWU/"
[10/Aug/2019:20:56:34 +1200] 502 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/tram.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
2019/08/10 20:56:34 [error] 493#493: *258 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-traccar, request: "GET /images/plane.svg HTTP/1.1", upstream: "http://127.0.0.1:18682/images/plane.svg", host: "hassio.local:8123", referrer: "http://hassio.local:8123/api/hassio_ingress/8chAPLNAS8E2tKXQnBJvPbYUqyOu-VyzJVSDZNbylWU/"
[10/Aug/2019:20:56:34 +1200] 502 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/plane.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
2019/08/10 20:56:34 [error] 493#493: *259 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-traccar, request: "GET /images/trolleybus.svg HTTP/1.1", upstream: "http://127.0.0.1:18682/images/trolleybus.svg", host: "hassio.local:8123", referrer: "http://hassio.local:8123/api/hassio_ingress/8chAPLNAS8E2tKXQnBJvPbYUqyOu-VyzJVSDZNbylWU/"
[10/Aug/2019:20:56:34 +1200] 502 192.168.1.194, 172.30.32.1(172.30.32.2) GET /images/trolleybus.svg HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
2019/08/10 20:56:34 [error] 493#493: *259 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-traccar, request: "GET /l10n/en.json?_dc=1565427394792 HTTP/1.1", upstream: "http://127.0.0.1:18682/l10n/en.json?_dc=1565427394792", host: "hassio.local:8123", referrer: "http://hassio.local:8123/api/hassio_ingress/8chAPLNAS8E2tKXQnBJvPbYUqyOu-VyzJVSDZNbylWU/"
[10/Aug/2019:20:56:34 +1200] 502 192.168.1.194, 172.30.32.1(172.30.32.2) GET /l10n/en.json?_dc=1565427394792 HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
2019/08/10 20:56:34 [error] 493#493: *259 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-traccar, request: "GET /l10n/en.json?_dc=1565427394792 HTTP/1.1", upstream: "http://127.0.0.1:18682/l10n/en.json?_dc=1565427394792", host: "hassio.local:8123", referrer: "http://hassio.local:8123/api/hassio_ingress/8chAPLNAS8E2tKXQnBJvPbYUqyOu-VyzJVSDZNbylWU/"
[10/Aug/2019:20:56:34 +1200] 502 192.168.1.194, 172.30.32.1(172.30.32.2) GET /l10n/en.json?_dc=1565427394792 HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
[20:56:34] INFO: Starting Traccar server...
```

## Steps to reproduce

> Start add-on, use it a bit, wait. Look at logs when webui is not working.

## Proposed changes

> I don't know how to fix it but happy to work to resolve, given some assistance.

### PR DESCRIPTION
**Pull request by tjorim**
# Proposed Changes

Upgrades the base image and packages

## Related Issues

Might fix #21, untested

### CODE REVIEW

**Comment by charlietomo** [comment]
I'm the author of #21 and happy to test but not sure how. I do not see it in Hass.io addon updates yet (still running (0.5.4). 
Thanks for the work on this.

**Comment by charlietomo** [comment]
@tjorim or @frenck should this fix be available? I am running latest hass and latest this and no change.
I see that a couple of `Pipelines` failed a couple of weeks ago; might this be related? https://gitlab.com/hassio-addons/addon-traccar/pipelines 
Appreciate your work on this.

**Comment by frenck** [comment]
@charlietomo It is not yet available.

**Comment by charlietomo** [comment]
> @charlietomo It is not yet available.

Is it waiting on a Traccar release or a hassos release? Look forward to the fix, or is there a way for me to test out in the meantime (e.g. a beta track)?

**Pull request merged**
